// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_zF2Qf-fTx0E1HmahAm7FZldNDcmkkN4',
    appId: '1:322270076998:web:40b1c797040b8585c56a47',
    messagingSenderId: '322270076998',
    projectId: 'dish-dash-65f40',
    authDomain: 'dish-dash-65f40.firebaseapp.com',
    storageBucket: 'dish-dash-65f40.appspot.com',
    measurementId: 'G-LPCBDTX90K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08f1TR_gQuMFrqhqNXvJxQEWaBidCUjY',
    appId: '1:322270076998:android:629f1ccbeea25f81c56a47',
    messagingSenderId: '322270076998',
    projectId: 'dish-dash-65f40',
    storageBucket: 'dish-dash-65f40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLPD7HIwIYa4_jw5rnB1dAPkQiCBhW8Y',
    appId: '1:322270076998:ios:d876f88f9e5c4d98c56a47',
    messagingSenderId: '322270076998',
    projectId: 'dish-dash-65f40',
    storageBucket: 'dish-dash-65f40.appspot.com',
    iosBundleId: 'com.example.dishdash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcLPD7HIwIYa4_jw5rnB1dAPkQiCBhW8Y',
    appId: '1:322270076998:ios:d876f88f9e5c4d98c56a47',
    messagingSenderId: '322270076998',
    projectId: 'dish-dash-65f40',
    storageBucket: 'dish-dash-65f40.appspot.com',
    iosBundleId: 'com.example.dishdash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_zF2Qf-fTx0E1HmahAm7FZldNDcmkkN4',
    appId: '1:322270076998:web:4ee530a394d58f24c56a47',
    messagingSenderId: '322270076998',
    projectId: 'dish-dash-65f40',
    authDomain: 'dish-dash-65f40.firebaseapp.com',
    storageBucket: 'dish-dash-65f40.appspot.com',
    measurementId: 'G-V0JML6K1GJ',
  );

}